name: hayan_app
description: A new Flutter project.



publish_to: 'none' 













version: 2.0.3+21

environment:
  sdk: '>=2.18.0-165.0.dev <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  panorama: ^0.4.1
  image_picker: ^0.8.5+3
  imageview360: ^1.3.0
  hidden_drawer_menu: ^3.0.1
  flutter_zoom_drawer: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/vr/
    - assets/sites.json
    - jsonfile/
    - assets/images/369/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
